name: Build Linux (Manual)

on:
  workflow_dispatch:

env:
  FREE_DISKSPACE: |
    sudo rm -rf /usr/local/.ghcup /usr/share/dotnet /usr/share/swift /usr/share/miniconda

jobs:
  build-linux-static:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: satackey/action-docker-layer-caching@v0.0.11
      if: "!startsWith(github.ref, 'refs/tags/v')"
      continue-on-error: true
      with:
        key: docker-linux-static-{hash}
        restore-keys: |
          docker-linux-static-

    - name: install dependencies
      run: sudo apt -y install xvfb libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xkb1 libxcb-shape0 libxkbcommon-x11-0 libegl1

    - name: free up diskspace
      run: ${{env.FREE_DISKSPACE}}

    - name: prepare build environment
      run: docker build --tag salvium:build-env-linux --build-arg THREADS=3 --file Dockerfile.linux .

    - name: build
      run: docker run --rm -v /home/runner/work/salvium-gui/salvium-gui:/salvium-gui -w /salvium-gui salvium:build-env-linux sh -c 'make release-static -j3'

    - name: sha256sum
      run: shasum -a256 /home/runner/work/salvium-gui/salvium-gui/build/release/bin/salvium-wallet-gui

    - name: test qml
      run: xvfb-run -a /home/runner/work/salvium-gui/salvium-gui/build/release/bin/salvium-wallet-gui --test-qml

    - uses: actions/upload-artifact@v4
      with:
        name: ${{ github.job }}
        path: |
          /home/runner/work/salvium-gui/salvium-gui/build/release/bin/salvium-wallet-gui
          /home/runner/work/salvium-gui/salvium-gui/build/release/bin/salviumd
