name: ci/gh-actions/gui

on:
  push:
    branches:
      - master

env:
  FREE_DISKSPACE: |
    sudo rm -rf /usr/local/.ghcup /usr/share/dotnet /usr/share/swift /usr/share/miniconda

jobs:
  build-macos-arm64:
    runs-on: macos-latest

    steps:
      - name: Check out code (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install dependencies (Homebrew)
        run: |
          brew install qt@5 boost@1.85 openssl@1.1 libsodium pkg-config cmake zeromq \
                       hidapi libpgm miniupnpc expat libunwind-headers protobuf ccache

      - name: Set up build environment paths
        run: |
          echo "CMAKE_PREFIX_PATH=/opt/homebrew/opt/qt@5:/opt/homebrew/opt/openssl@1.1:/opt/homebrew/opt/boost@1.85:/opt/homebrew/opt/libsodium:/opt/homebrew/opt/miniupnpc:/opt/homebrew/opt/protobuf" >> $GITHUB_ENV
          echo "/opt/homebrew/opt/qt@5/bin" >> $GITHUB_PATH

      - name: Configure CMake
        run: |
          mkdir -p build/release
          cd build/release
          cmake -D CMAKE_BUILD_TYPE=Release \
                -D DEV_MODE=OFF \
                -D MANUAL_SUBMODULES=OFF \
                -D CMAKE_POLICY_DEFAULT_CMP0074=NEW \
                -D Boost_INCLUDE_DIR=/opt/homebrew/opt/boost@1.85/include \
                -D Boost_LIBRARY_DIR=/opt/homebrew/opt/boost@1.85/lib \
                -D CMAKE_EXE_LINKER_FLAGS="-L/opt/homebrew/opt/openssl@1.1/lib" \
                -D CMAKE_CXX_FLAGS="-I/opt/homebrew/opt/boost@1.85/include" \
                ../..
        env:
           CMAKE_PREFIX_PATH: ${{ env.CMAKE_PREFIX_PATH }}

      - name: Build with Make
        run: |
          cd build/release
          make -j$(sysctl -n hw.ncpu)

      - name: Test QML
        if: success()
        run: |
          cd build/release/bin
          ./salvium-wallet-gui.app/Contents/MacOS/salvium-wallet-gui --test-qml

      - name: Create unsigned .dmg
        if: success()
        run: |
          hdiutil create -fs HFS+ -srcfolder build/release/bin/salvium-wallet-gui.app -volname "salvium-gui" salvium-gui-unsigned.dmg

      - name: SHA256 Sum DMG
        if: success()
        run: shasum -a 256 salvium-gui-unsigned.dmg

      - name: Upload Artifact (Unsigned .dmg)
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: salvium-gui-macos-arm64-unsigned
          path: salvium-gui-unsigned.dmg

  build-windows:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Build Docker Image for Windows Env
        run: |
          docker build --tag salvium:build-env-windows \
                       --build-arg THREADS=$(nproc) \
                       -f Dockerfile.windows .

      - name: Compile Salvium GUI (Windows Target)
        run: |
          docker run --rm --user $(id -u):$(id -g) \
          -v "${{ github.workspace }}":/salvium-gui \
          -w /salvium-gui salvium:build-env-windows \
          sh -c 'make depends root=/depends target=x86_64-w64-mingw32 tag=win-x64 -j$(nproc)'

      - name: SHA256 Sum EXE
        if: success()
        run: |
          EXE_PATH=$(find build/x86_64-w64-mingw32/release/bin -name 'salvium-wallet-gui.exe' | head -n 1)
          if [ -f "$EXE_PATH" ]; then
            sha256sum "$EXE_PATH"
          else
            echo "Windows EXE not found at expected path!"
            exit 1
          fi

      - name: Upload Artifact (Windows Build Output)
        uses: actions/upload-artifact@v4
        with:
          name: salvium-gui-windows-x64
          path: build/x86_64-w64-mingw32/release/bin/

  docker-linux-static:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: satackey/action-docker-layer-caching@v0.0.11
      if: "!startsWith(github.ref, 'refs/tags/v')"
      continue-on-error: true
      with:
        key: docker-linux-static-{hash}
        restore-keys: |
          docker-linux-static-
    - name: install host dependencies (for xvfb)
      run: sudo apt update && sudo apt -y install xvfb libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xkb1 libxcb-shape0 libxkbcommon-x11-0 libegl1
    - name: free up diskspace
      run: ${{env.FREE_DISKSPACE}}
    - name: prepare build environment (Docker)
      run: docker build --tag salvium:build-env-linux --build-arg THREADS=$(nproc) --file Dockerfile.linux .
    - name: build (inside Docker)
      run: docker run --rm -v ${{ github.workspace }}:/salvium-gui -w /salvium-gui salvium:build-env-linux sh -c 'make release-static -j$(nproc)'
    - name: sha256sum Binary
      run: sha256sum build/release/bin/salvium-wallet-gui
    - name: test qml
      run: xvfb-run -a ${{ github.workspace }}/build/release/bin/salvium-wallet-gui --test-qml
    - uses: actions/upload-artifact@v4
      with:
        name: salvium-gui-linux-x64-static
        path: |
          build/release/bin/salvium-wallet-gui
          build/release/bin/salviumd

  docker-android:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: satackey/action-docker-layer-caching@v0.0.11
      if: "!startsWith(github.ref, 'refs/tags/v')"
      continue-on-error: true
      with:
        key: docker-android-{hash}
        restore-keys: |
          docker-android-
    - name: free up diskspace
      run: ${{env.FREE_DISKSPACE}}

    - name: Build Android APK via Docker
      run: |
        docker build --tag salvium:android-build-final \
                     --build-arg THREADS=$(nproc) \
                     --file Dockerfile.android .
    - name: Extract APK from Docker Image
      run: |
        docker run --name temp_salvium_apk salvium:android-build-final
        mkdir -p ./android_apk_output
        docker cp temp_salvium_apk:/salvium-apk ./android_apk_output
        docker rm temp_salvium_apk
    - name: SHA256 Sum APK
      run: |
        APK_FILE=$(find ./android_apk_output -name '*.apk' | head -n 1)
        if [ -f "$APK_FILE" ]; then
          sha256sum "$APK_FILE"
        else
          echo "Android APK not found in ./android_apk_output!"
          exit 1
        fi

    - uses: actions/upload-artifact@v4
      with:
        name: salvium-gui-android-arm64-v8a
        path: ./android_apk_output/
