name: ci/gh-actions/gui

on: [push, pull_request]

env:
  FREE_DISKSPACE: |
    sudo rm -rf /usr/local/.ghcup /usr/share/dotnet /usr/share/swift /usr/share/miniconda

jobs:
  build-macos-arm64:
    runs-on: macos-latest

    steps:
      - name: Check out code (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install dependencies (Homebrew)
        run: |
          brew install qt@5 boost@1.85 openssl@1.1 libsodium pkg-config cmake zeromq \
                       hidapi libpgm miniupnpc expat libunwind-headers protobuf ccache

      - name: Set up build environment paths
        run: |
          echo "CMAKE_PREFIX_PATH=/opt/homebrew/opt/qt@5:/opt/homebrew/opt/openssl@1.1:/opt/homebrew/opt/boost@1.85:/opt/homebrew/opt/libsodium:/opt/homebrew/opt/miniupnpc:/opt/homebrew/opt/protobuf" >> $GITHUB_ENV
          echo "/opt/homebrew/opt/qt@5/bin" >> $GITHUB_PATH

      - name: Configure CMake
        run: |
          mkdir -p build/release
          cd build/release
          /opt/homebrew/bin/cmake -D CMAKE_BUILD_TYPE=Release \
                -D DEV_MODE=OFF \
                -D MANUAL_SUBMODULES=OFF \
                -D CMAKE_POLICY_DEFAULT_CMP0074=NEW \
                -D Boost_INCLUDE_DIR=/opt/homebrew/opt/boost@1.85/include \
                -D Boost_LIBRARY_DIR=/opt/homebrew/opt/boost@1.85/lib \
                -D CMAKE_EXE_LINKER_FLAGS="-L/opt/homebrew/opt/openssl@1.1/lib" \
                -D CMAKE_CXX_FLAGS="-I/opt/homebrew/opt/boost@1.85/include" \
                ../..
        env:
           CMAKE_PREFIX_PATH: ${{ env.CMAKE_PREFIX_PATH }}

      - name: Build with Make
        run: |
          cd build/release
          make -j$(sysctl -n hw.ncpu)

      - name: Create unsigned .dmg
        if: success()
        run: |
          hdiutil create -fs HFS+ -srcfolder build/release/bin/salvium-wallet-gui.app -volname "salvium-gui" salvium-gui-unsigned.dmg

      - name: Upload Artifact (Unsigned .dmg)
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: salvium-gui-macos-arm64-unsigned
          path: salvium-gui-unsigned.dmg

  build-windows:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Build Docker Image
        run: |
          docker build --tag salvium:build-env-windows \
                       --build-arg THREADS=$(nproc) \
                       -f Dockerfile.windows .

      - name: Compile Salvium GUI
        run: |
          docker run --rm --user $(id -u):$(id -g) \
          -v "${{ github.workspace }}":/salvium-gui \
          -w /salvium-gui salvium:build-env-windows \
          sh -c 'make depends root=/depends target=x86_64-w64-mingw32 tag=win-x64 -j$(nproc)'

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: salvium-gui-windows
          path: build/

  docker-linux-static:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - uses: satackey/action-docker-layer-caching@v0.0.11
      if: "!startsWith(github.ref, 'refs/tags/v')"
      continue-on-error: true
      with:
        key: docker-linux-static-{hash}
        restore-keys: |
          docker-linux-static-
    - name: install dependencies
      run: sudo apt -y install xvfb libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xkb1 libxcb-shape0 libxkbcommon-x11-0
    - name: free up diskspace
      run: ${{env.FREE_DISKSPACE}}
    - name: prepare build environment
      run: docker build --tag salvium:build-env-linux --build-arg THREADS=3 --file Dockerfile.linux .
    - name: build
      run: docker run --rm -v /home/runner/work/salvium-gui/salvium-gui:/salvium-gui -w /salvium-gui salvium:build-env-linux sh -c 'make release-static -j3'
    - name: sha256sum
      run: shasum -a256 /home/runner/work/salvium-gui/salvium-gui/build/release/bin/salvium-wallet-gui
    - name: test qml
      run: xvfb-run -a /home/runner/work/salvium-gui/salvium-gui/build/release/bin/salvium-wallet-gui --test-qml
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ github.job }}
        path: |
          /home/runner/work/salvium-gui/salvium-gui/build/release/bin/salvium-wallet-gui
          /home/runner/work/salvium-gui/salvium-gui/build/release/bin/salviumd

  docker-android:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - uses: satackey/action-docker-layer-caching@v0.0.11
      if: "!startsWith(github.ref, 'refs/tags/v')"
      continue-on-error: true
      with:
        key: docker-android-static-{hash}
        restore-keys: |
          docker-android-static-
    - name: free up diskspace
      run: ${{env.FREE_DISKSPACE}}
    - name: prepare build environment
      run: docker build --tag salvium:build-env-android --build-arg THREADS=3 --file Dockerfile.android .
    - name: build
      run: docker run --rm -v /home/runner/work/salvium-gui/salvium-gui:/salvium-gui -e THREADS=3 salvium:build-env-android
    - name: Remove obsolete docker layers
      run: docker images -a | grep none | awk '{ print $3; }' | xargs docker rmi || true
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ github.job }}
        path: /home/runner/work/salvium-gui/salvium-gui/build/Android/release/android-build/salvium-gui.apk
